// ((list price - actual price) / (list price)) * 100%

const products = [
    {
        title: 'Wild King Salmon Fish',
        price: 15,
        offerPrice: 12,
        details:
            'A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.',
        unit: '1lb',
        stock: 20,
        tags: ['fresh', 'sea', 'food', 'salmon', 'fish', 'steak'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653452590/MBbazar/Products/Salmon-Steak_tbuywv.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653452581/MBbazar/Products/salmon-steak2_hjeoad.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653452577/MBbazar/Products/salmon-streak3_bsfxyn.webp',
        ],
        featured: ['popular', 'bestSell', 'dealOfTheDay'],
        category: 'Fish',
        sold: 120,
    },
    {
        title: 'Ling Cod Steak',
        price: 15,
        offerPrice: 11,
        details:
            'A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.',
        unit: '1lb',
        stock: 10,
        tags: ['fresh', 'sea', 'food', 'ling', 'cod', 'steak'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653453477/MBbazar/Products/Ling-Cod-Steak_lqxkn0.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653453479/MBbazar/Products/ling-cod-steak3_v59gih.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653453478/MBbazar/Products/ling-cod-steak2_ea6f5n.jpg',
        ],
        featured: [],
        category: 'Fish',
        sold: 30,
    },
    {
        title: 'Rui Fish',
        price: 8,
        offerPrice: 4,
        details:
            'The Rui fish is a species of freshwater fish of the carp family. It is found mainly in rivers in South Asia. It is known by many different names such as rohu, rohit or roho. It is the most important among the 3 Indian major carp fish species used in polyculture systems.Rui fish is highly available throughout northern and central India, Nepal, Bangladesh, Pakistan and Myanmar. It has also been introduced in many other countries, including, China, Japan, Sri Lanka, Philippines and some countries of Africa. The traditional culture of this carp fish goes back hundreds of years in the small ponds of the eastern Indian states, and Bangladesh.The compatibility of Rui fish with other carps like Catla and Mrigal made it an ideal candidate for carp polyculture system. Emphasis has been given to it’s genetic improvement through selective breeding in India, considering it’s importance in the culture system.',
        unit: '1kg',
        stock: 100,
        tags: ['fresh', 'river', 'fish', 'pond', 'hawor', 'rui'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653454215/MBbazar/Products/rohu-fish_mnfk4k.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653454232/MBbazar/Products/rui-fish3_wlefaq.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653454231/MBbazar/Products/rui-fish2_oyospb.webp',
        ],
        featured: ['popular', 'bestSell'],
        category: 'Fish',
        sold: 200,
    },
    {
        title: 'Hilsha Fish',
        price: 12,
        offerPrice: 10,
        details:
            'Hilsa (ilish) any of the members of the genus Tenualosa of the family Clupeidae, order Clupeiformes. Locally known as Ilish, the fish has been designated as the national fish of Bangladesh. The body is strongly compressed and moderately deep with dorsal and ventral profile equally convex. The upper jaw has a distinct median notch. Regularly arranged medium-sized scales cover the metallic silver-coloured body. Body length may reach up to 60 cm, but commonly found specimens measure 35 to 40 cm. A large-sized hilsa weighs about 2.5 kg. Females grow faster, and are usually larger than males. The hilsa is known to be a fast swimmer, and attains maturity in one to two years.Hilsa has a wide range of distribution and occurs in marine, estuarine and riverine environments. The fish is found in the Persian Gulf, Red Sea, Arabian Sea, Bay of Bengal, Vietnam Sea and China Sea. The riverine habitat covers the Satil Arab, and the Tigris and Euphrates of Iran and Iraq, the Indus of Pakistan, the rivers of Eastern and Western India, the Irrawaddy of Myanmar, and the Padma, Jamuna, Meghna, Karnafully and other coastal rivers of Bangladesh.',
        unit: '1kg',
        stock: 30,
        tags: ['fresh', 'river', 'fish', 'Hilsha', 'ilish', 'elish'],
        onSale: true,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653454630/MBbazar/Products/hilsha-fish2_nosxwn.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653454628/MBbazar/Products/hilsa-fish_asdodw.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653454631/MBbazar/Products/hilsa-fish3_mpfjnv.jpg',
        ],
        featured: ['popular', 'bestSell'],
        category: 'Fish',
        sold: 500,
    },
    {
        title: 'Katla Fish',
        price: 4,
        offerPrice: 2,
        details:
            'It is known by many different names such as Katla, Katol, Indian Major carp, Chepti, Baudhekra, Bacha, Karakatla and Tambra.The fish is mainly found in the rives and lakes in northern India, Bangladesh, Nepal, Pakistan and Myanmar.The Catla fish is a freshwater species, and it is found rarely in brakish water. Some common habitats of this fish species are baors, beels, canals, ditch, floodplains, haors, lake, ponds and lakes.The fish is generally marketed in fresh condition, and it command a good market price and consumer demand.',
        unit: '1kg',
        stock: 20,
        tags: ['fresh', 'river', 'fish', 'katla', 'catla', 'pond', 'hawor'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455274/MBbazar/Products/katla-fish_ionoho.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455274/MBbazar/Products/katla-fish2_xjugae.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455274/MBbazar/Products/katla-fish3_dtxsfs.jpg',
        ],
        featured: [],
        category: 'Fish',
        sold: 80,
    },
    {
        title: 'Rupchanda Fish',
        price: 8,
        offerPrice: 6,
        details:
            'A seawater fish having one single bone, Rupchand (also known as Chinese Pomfret) comes with a flattened body with a deeply forked tail. This popular menu item is cooked fresh and is either steamed or fried.',
        unit: '1kg',
        stock: 20,
        tags: ['fresh', 'sea', 'fish', 'rupchada', 'rupchanda', 'roopchada'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455630/MBbazar/Products/rupchanda_hfxzru.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455630/MBbazar/Products/rupchanda-fish3_z7ek8w.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455630/MBbazar/Products/rupchanda-fish2_iv08ow.jpg',
        ],
        featured: [],
        category: 'Fish',
        sold: 300,
    },
    {
        title: 'Boal Fish',
        price: 4,
        offerPrice: 2,
        details:
            'Boal fish is a species of catfish. They are cannibalistic in nature. Boal fish can found in lakes, swamp or large rivers. It is a fish species of south Asia.This fish species found in Bangladesh, India, Pakistan, Vietnam, Indonesia, Afghanistan and some other countries.This fish is also known by some other names like wallago, wallagonia attu, borali etc. Due to its ferocity it is also known as freshwater shark.Boal is a freshwater fish.',
        unit: '1kg',
        stock: 20,
        tags: ['fresh', 'river', 'fish', 'boal', 'bual', 'pond', 'hawor'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455630/MBbazar/Products/boal-fish_tsibcn.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455630/MBbazar/Products/boal-fish3_od2ip1.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653455631/MBbazar/Products/boal-fish2_ci76tb.jpg',
        ],
        featured: [],
        category: 'Fish',
        sold: 60,
    },
    {
        title: 'Chicken Meat',
        price: 3,
        offerPrice: 3,
        details:
            'Chicken meat contains about two to three times as much polyunsaturated fat as most types of red meat when measured as weight percentage.Chicken generally includes low fat in the meat itself (castrated roosters excluded). The fat is highly concentrated on the skin. A 100g serving of baked chicken breast contains 4 grams of fat and 31 grams of protein, compared to 10 grams of fat and 27 grams of protein for the same portion of broiled, lean skirt steak.',
        unit: '1kg',
        stock: 200,
        tags: ['fresh', 'chicken', 'meat', 'murgi', 'farm'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/chicken-meat2_cugeoo.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/chicken-meat_mtfi4s.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/desi-chicken3_qplg01.jpg',
        ],
        featured: ['popular'],
        category: 'Meat',
        sold: 200,
    },
    {
        title: 'Desi Chicken Meat',
        price: 5,
        offerPrice: 4,
        details:
            'Chicken meat contains about two to three times as much polyunsaturated fat as most types of red meat when measured as weight percentage.Chicken generally includes low fat in the meat itself (castrated roosters excluded). The fat is highly concentrated on the skin. A 100g serving of baked chicken breast contains 4 grams of fat and 31 grams of protein, compared to 10 grams of fat and 27 grams of protein for the same portion of broiled, lean skirt steak.',
        unit: '1kg',
        stock: 200,
        tags: ['fresh', 'chicken', 'meat', 'murgi', 'desi', 'deshi'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/desi-chicken2_otheaq.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/desi-chicken-meat_phyhwo.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/desi-chicken3_qplg01.jpg',
        ],
        featured: ['popular'],
        category: 'Meat',
        sold: 200,
    },
    {
        title: 'Beaf Meat',
        price: 8,
        offerPrice: 7,
        details:
            'beef, flesh of mature cattle, as distinguished from veal, the flesh of calves. The best beef is obtained from early maturing, special beef breeds. High-quality beef has firm, velvety, fine-grained lean, bright red in colour and well-marbled. The fat is smooth, creamy white, and well distributed.',
        unit: '1kg',
        stock: 200,
        tags: ['fresh', 'beaf', 'meat', 'goru', 'cow'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/beaf-meat3_crefjd.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/beaf-meat_t2wsga.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653459889/MBbazar/Products/beaf-meat3_ipuko4.jpg',
        ],
        featured: ['popular', 'dealsOfTheDay', 'bestSell'],
        category: 'Meat',
        sold: 600,
    },
    {
        title: 'Duck Meat',
        price: 6,
        offerPrice: 4,
        details:
            'Ducks, or ducklings as they are also referred, should be no more than six months old and weigh 3 to 7 pounds providing a tender rich meat for cooking. Ducks most suitable for broiling or frying are classified as "broilers" or "fryers" when they are no older than 8 weeks. Ducks that are 8 to 16 weeks old have gained more fat and are then classified as "roasters" which are most suitable for roasting or cooking with a rotisserie grill. The meat of a duck is all dark meat, providing a distinctively hearty flavor that may be rich tasting, depending on the method and procedures for preparation. Wild duck has more of a "gamey" flavor having been raised on wild foods. Domestic ducks are more moist and tender, providing a milder flavored meat. ',
        unit: '1kg',
        stock: 30,
        tags: ['fresh', 'duck', 'meat', 'hash'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/duck-meat2_f1bz4n.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456442/MBbazar/Products/duck-meat3_b2tf8o.jpg',
        ],
        featured: [],
        category: 'Meat',
        sold: 30,
    },
    {
        title: 'Mutton',
        price: 7,
        offerPrice: 6,
        details:
            'Mutton refers to the flesh of the mature ram or ewe at least one year old; the meat of sheep between 12 and 20 months old may be called yearling mutton. The meat of sheep 6 to 10 weeks old is usually sold as baby lamb, and spring lamb is from sheep of age five to six months',
        unit: '1kg',
        stock: 200,
        tags: ['fresh', 'goat', 'meat', 'mutton', 'chagol'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456443/MBbazar/Products/mutton-meat3_gvglxw.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456443/MBbazar/Products/mutton_zb7dfk.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653456443/MBbazar/Products/mutton-meat2_tb5piq.jpg',
        ],
        featured: ['popular'],
        category: 'Meat',
        sold: 400,
    },
    {
        title: 'Golden garden love palm',
        price: 12,
        offerPrice: 10,
        details:
            'Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators. ... Nearly half of the dried fruits sold are raisins, followed by dates, prunes, figs, apricots, peaches, apples, and pears.',
        unit: '1kg',
        stock: 100,
        tags: ['dry', 'fruit', 'golden', 'love', 'palm'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653461086/MBbazar/Products/Golden-Garden-Love-Plum2_rzmu3n.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653461085/MBbazar/Products/golden-garden-palm_tzsndw.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653461087/MBbazar/Products/golden-garden-palm3_aqz1hl.jpg',
        ],
        featured: [],
        category: 'Dry Fruits',
        sold: 50,
    },
    {
        title: 'Golden Garden Blueberry Plum',
        price: 12,
        offerPrice: 10,
        details:
            'Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators. ... Nearly half of the dried fruits sold are raisins, followed by dates, prunes, figs, apricots, peaches, apples, and pears.',
        unit: '1kg',
        stock: 100,
        tags: ['dry', 'fruit', 'blueberry', 'golden', 'palm'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653461300/MBbazar/Products/golden-garden-bluberry-palm_tuh2mm.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653461317/MBbazar/Products/golden-garden-blueberry-palm2_qsj6qf.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653461309/MBbazar/Products/Golden-Garden-Blueberry-Plum3_cjpcgh.webp',
        ],
        featured: [],
        category: 'Dry Fruits',
        sold: 50,
    },
    {
        title: 'Orange Fruit',
        price: 8,
        offerPrice: 6,
        details: `The term orange may refer to a number of citrus trees that produces fruit for people to eat. Oranges are a very good source of Vitamin C.[1] Orange juice is an important part of many people's breakfast. The "sweet orange", which is the kind that are most often eaten today, grew first in South and East Asia but now grows in lots of parts of the world.Oranges are round orange-coloured fruit that grow on a tree which can reach 10 metres (33 ft) high. Orange trees have dark green shiny leaves and small white flowers with five petals. The flowers smell very sweet which attracts many bees.`,
        unit: '1kg',
        stock: 100,
        tags: ['fresh', 'fruit', 'orange', 'komla', 'komola', 'comola'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653540132/MBbazar/Products/orange_a3ryct.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653540133/MBbazar/Products/orange2_dtr5hm.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653540133/MBbazar/Products/orange3_o2ays5.jpg',
        ],
        featured: [],
        category: 'Fresh Fruits',
        sold: 54,
    },
    {
        title: 'Strawberry Fruit',
        price: 5,
        offerPrice: 3,
        details: `A strawberry is both a low-growing, flowering plant and also the name of the fruit that it produces. Strawberries are soft, sweet, bright red berries. They're also delicious.Strawberries have tiny edible seeds, which grow all over their surface. When ripe, strawberries smell wonderful and taste even better.Strawberries are low-growing herbaceous plants with a fibrous root system and a crown from which arise basal leaves. The leaves are compound, typically with three leaflets, sawtooth-edged, and usually hairy. The flowers, generally white, rarely reddish, are borne in small clusters on slender stalks arising, like the surface-creeping stems, from the axils of the leaves. As a plant ages, the root system becomes woody, and the “mother” crown sends out runners (e.g., stolons) that touch ground and root, thus enlarging the plant vegetatively. Botanically, the strawberry fruit is considered an “accessory fruit” and is not a true berry. The flesh consists of the greatly enlarged flower receptacle and is embedded with the many true fruits, or achenes, which are popularly called seeds.`,
        unit: '1kg',
        stock: 100,
        tags: ['fresh', 'fruit', 'strawberry', 'strawberries', 'stroberry'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653542368/MBbazar/Products/Strawberries_gwpwfw.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653542369/MBbazar/Products/Strawberries2_d11yif.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653542370/MBbazar/Products/strawberries3_p38f1w.jpg',
        ],
        featured: [],
        category: 'Fresh Fruits',
        sold: 70,
    },
    {
        title: 'Cauliflower',
        price: 2,
        offerPrice: 0.6,
        details: `Cauliflower is one of several vegetables in the species Brassica oleracea in the genus Brassica, which is in the Brassicaceae (or mustard) family. It is an annual plant that reproduces by seed. Typically, only the head is eaten – the edible white flesh sometimes called "curd" (with a similar appearance to cheese curd).[1] The cauliflower head is composed of a white inflorescence meristem. Cauliflower heads resemble those in broccoli, which differs in having flower buds as the edible portion. Brassica oleracea also includes broccoli, Brussels sprouts, cabbage, collard greens, and kale, collectively called "cole" crops,[2] though they are of different cultivar groups.`,
        unit: '1kg',
        stock: 100,
        tags: ['fresh', 'vegetable', 'cauliflower', 'fulcopi', 'fulkopi', 'fullkopi'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653543825/MBbazar/Products/fulkopi_ycyfhc.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653543825/MBbazar/Products/fulcopi2_wxkdz3.jpg',
        ],
        featured: [],
        category: 'Fresh Vegetables',
        sold: 180,
    },
    {
        title: 'Fresh soyabean oil',
        price: 10,
        offerPrice: 9,
        details: `Cooking oil is plant, animal, or synthetic fat used in frying, baking, and other types of cooking. ... Cooking oil is typically a liquid at room temperature, although some oils that contain saturated fat, such as coconut oil, palm oil and palm kernel oil are solid.`,
        unit: '5L',
        stock: 100,
        tags: ['fresh', 'soyabean', 'oil', 'soyabin'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653546668/MBbazar/Products/Fresh-Soyabean-Oil-5-Ltr_j9nyzy.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653546646/MBbazar/Products/fresh-oil_fivgw4.jpg',
        ],
        featured: ['popular'],
        category: 'Oil',
        sold: 380,
    },
    {
        title: 'Fresh Chinigura Rice',
        price: 2.5,
        offerPrice: 1.5,
        details: `rice, (Oryza sativa), edible starchy cereal grain and the grass plant (family Poaceae) by which it is produced. ... Rice is cooked by boiling, or it can be ground into a flour. It is eaten alone and in a great variety of soups, side dishes, and main dishes in Asian, Middle Eastern, and many other cuisines.`,
        unit: '2kg',
        stock: 100,
        tags: ['fresh', 'chinigura', 'rice', 'chal'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653547087/MBbazar/Products/Fresh-Chinigura-Rice-1kg_ruhify.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653547088/MBbazar/Products/Chinigura-rice_ou2rry.jpg',
        ],
        featured: ['bestSell'],
        category: 'Rice',
        sold: 780,
    },
    {
        title: 'Fresh Flour',
        price: 1.7,
        offerPrice: 1.5,
        details: `Flour, finely ground cereal grains or other starchy portions of plants, used in various food products and as a basic ingredient of baked goods. Flour made from wheat grains is the most satisfactory type for baked products that require spongy structure. ... The outer layers and internal structures of a kernel of wheat.`,
        unit: '1kg',
        stock: 100,
        tags: ['fresh', 'flour', 'atta', 'ata'],
        onSale: true,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653547489/MBbazar/Products/Fresh-Atta-2-Kg_p8zevd.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653547490/MBbazar/Products/fresh-atta2_aofnvy.jpg',
        ],
        featured: [],
        category: 'Flour',
        sold: 90,
    },
    {
        title: 'Onion',
        price: 0.6,
        offerPrice: 0.6,
        details: `Any vegetable that has been dehydrated or dried in order to extend the shelf life and to concentrate the flavor. Popular dried vegetables include sun-dried tomatoes, onions, carrots, and chiles.`,
        unit: '1kg',
        stock: 100,
        tags: ['dry', 'onion', 'vegetable', 'peyaj', 'piyaj'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653547829/MBbazar/Products/onion_ppve9z.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653547829/MBbazar/Products/onion2_l1yz9m.jpg',
        ],
        featured: ['popular'],
        category: 'Dry Vegetables',
        sold: 200,
    },
    {
        title: 'ACI Pure Salt',
        price: 6,
        offerPrice: 5,
        details: `Spice mixes are blended spices or herbs. ... Blends such as chili powder, curry powder, herbes de Provence, garlic salt, and other seasoned salts are traditionally sold pre-made by grocers, and sometimes baking blends such as pumpkin pie spice are also available.`,
        unit: '750g',
        stock: 100,
        tags: ['salt', 'lobon'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653548114/MBbazar/Products/ACI-Pure-Salt-Jar_opjrzs.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653548115/MBbazar/Products/aci-salt2_oehz3b.jpg',
        ],
        featured: [],
        category: 'Spices & Mixes',
        sold: 30,
    },
    {
        title: 'Bread',
        price: 1,
        offerPrice: 0.7,
        details: `The definition of a breakfast food is a food that is eaten primarily for the first meal of the day commonly including: cereal, toast, eggs, pancakes, waffles, pastries, sausage or bacon. An example of a breakfast food is oatmeal. An example of a breakfast food is french toast with scrambled eggs.`,
        unit: '1pc',
        stock: 100,
        tags: ['bread', 'breakfast', 'paoruti', 'pauruti'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653548250/MBbazar/Products/bread_captpu.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653548250/MBbazar/Products/bread_captpu.webp',
        ],
        featured: [],
        category: 'Bread',
        sold: 50,
    },
    {
        title: 'Koko Crunch',
        price: 6,
        offerPrice: 5,
        details: `The definition of a breakfast food is a food that is eaten primarily for the first meal of the day commonly including: cereal, toast, eggs, pancakes, waffles, pastries, sausage or bacon. An example of a breakfast food is oatmeal. An example of a breakfast food is french toast with scrambled eggs.`,
        unit: '1pc',
        stock: 100,
        tags: ['cereal', 'breakfast', 'kokokrunch', 'chocolate'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653548662/MBbazar/Products/koko-crunch_ml6eiy.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653548667/MBbazar/Products/koko-krunch2_ppnfyz.jpg',
        ],
        featured: [],
        category: 'Cereal',
        sold: 50,
    },
    {
        title: 'Ispahani Mirzapur Tea',
        price: 5,
        offerPrice: 4,
        details: `Tea is an aromatic beverage prepared by pouring hot or boiling water over cured or fresh leaves of Camellia sinensis, an evergreen shrub native to China and East Asia. After water, it is the most widely consumed drink in the world. ... Tea has a stimulating effect in humans primarily due to its caffeine content.`,
        unit: '400g',
        stock: 100,
        tags: ['tea', 'ispahani', 'mirzapur', 'cha', 'chapata'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549164/MBbazar/Products/ispahani-tea_mu0kkl.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549178/MBbazar/Products/ispahani-tea2_unoobt.jpg',
        ],
        featured: [],
        category: 'Tea',
        sold: 334,
    },
    {
        title: 'Fresh Drinking Water',
        price: 0.6,
        offerPrice: 0.4,
        details: `water, a substance composed of the chemical elements hydrogen and oxygen and existing in gaseous, liquid, and solid states. It is one of the most plentiful and essential of compounds. A tasteless and odourless liquid at room temperature, it has the important ability to dissolve many other substances.`,
        unit: '2L',
        stock: 100,
        tags: ['fresh', 'drinking', 'water', 'pani'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549323/MBbazar/Products/fresh-water_e6aabr.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549325/MBbazar/Products/fresh-water2_qfawbu.jpg',
        ],
        featured: [],
        category: 'Water',
        sold: 334,
    },
    {
        title: 'Tang Juice',
        price: 5,
        offerPrice: 3,
        details: `Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice.`,
        unit: '500g',
        stock: 100,
        tags: ['tang', 'juice', 'shorbot'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549562/MBbazar/Products/tang_gcyajc.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549562/MBbazar/Products/tang2_skmr2e.jpg',
        ],
        featured: [],
        category: 'Juice',
        sold: 534,
    },
    {
        title: 'Marley Coffee',
        price: 8,
        offerPrice: 6,
        details: `Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain Coffea species. ... Coffee is darkly colored, bitter, slightly acidic and has a stimulating effect in humans, primarily due to its caffeine content.`,
        unit: '500g',
        stock: 100,
        tags: ['coffee', 'marley', 'cafe', 'drink'],
        onSale: true,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549562/MBbazar/Products/tang_gcyajc.webp',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549562/MBbazar/Products/tang2_skmr2e.jpg',
        ],
        featured: [],
        category: 'Coffee',
        sold: 134,
    },
    {
        title: 'Coke',
        price: 1.5,
        offerPrice: 0.8,
        details: `Energy drink, any beverage that contains high levels of a stimulant ingredient, usually caffeine, as well as sugar and often supplements, such as vitamins or carnitine, and that is promoted as a product capable of enhancing mental alertness and physical performance.`,
        unit: '1L',
        stock: 100,
        tags: ['coke', 'soft', 'enargy', 'drink'],
        onSale: true,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549956/MBbazar/Products/coke_eb8t2f.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653549957/MBbazar/Products/coke2_thogr9.png',
        ],
        featured: ['popular'],
        category: 'Enargy Drink',
        sold: 834,
    },
    {
        title: 'Arong Milk',
        price: 5,
        offerPrice: 3,
        details: `a room, building, or establishment where milk is kept and butter or cheese is made. 2a : the department of farming or of a farm that is concerned with the production of milk, butter, and cheese. b : a farm devoted to such production.`,
        unit: '1L',
        stock: 100,
        tags: ['milk', 'arong', 'dud', 'dudh', 'goru'],
        onSale: true,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710410/MBbazar/Products/uht-500-405x330_kjjert.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710410/MBbazar/Products/images_6_hcbjvi.jpg',
        ],
        featured: ['popular', 'dealsOfTheDay', 'bestSell'],
        category: 'Dairy',
        sold: 100,
    },
    {
        title: 'Igloo Vanilla Cup Ice Cream',
        price: 2,
        offerPrice: 1,
        details: `Ice cream is a frozen dairy dessert obtained by freezing the ice cream mix with continuous agitation. It contains milk products, sweetening materials, stabilizers, colors, flavors, and egg products. Ice cream had its origins in Europe and was introduced later in the United States where it developed into an industry.`,
        unit: '100ml',
        stock: 100,
        tags: ['cup', 'ice', 'cream', 'ice cream'],
        onSale: true,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710410/MBbazar/Products/Igloo-Cup-Vanilla-100-Ml_upu6co.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710411/MBbazar/Products/download_yarngp.jpg',
        ],
        featured: ['popular', 'dealsOfTheDay', 'bestSell'],
        category: 'Ice Cream',
        sold: 454,
    },
    {
        title: 'Pran Premium Ghee',
        price: 10,
        offerPrice: 8,
        details: `Butter, a yellow-to-white solid emulsion of fat globules, water, and inorganic salts produced by churning the cream from cows' milk. ... Butter is a high-energy food, containing approximately 715 calories per 100 grams. It has a high content of butterfat, or milk fat (at least 80 percent), but is low in protein.`,
        unit: '200gm',
        stock: 100,
        tags: ['pran', 'premium', 'ghee', 'ghi'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710411/MBbazar/Products/Pran-Premium-Ghee_maxbue.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710411/MBbazar/Products/pran-premium-ghee_gaiyyt.png',
        ],
        featured: ['popular', 'dealsOfTheDay', 'bestSell'],
        category: 'Butter & Ghee',
        sold: 654,
    },
    {
        title: 'Alshifa Natural Honey',
        price: 20,
        offerPrice: 17,
        details: `honey, sweet, viscous liquid food, dark golden in colour, produced in the honey sacs of various bees from the nectar of flowers. Flavour and colour are determined by the flowers from which the nectar is gathered. Some of the most commercially desirable honeys are produced from clover by the domestic honeybee.`,
        unit: '250gm',
        stock: 100,
        tags: ['alshifa', 'natural', 'honey', 'modhu'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/Alshifa-Natural-Honey-250-Gm_kyj5ld.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/alshifa-sugar-free-jelly_y2os2i.jpg',
        ],
        featured: ['popular', 'dealsOfTheDay', 'bestSell'],
        category: 'Honey',
        sold: 12,
    },
    {
        title: 'Life Soya Sauce',
        price: 20,
        offerPrice: 17,
        details: `sauce, liquid or semiliquid mixture that is added to a food as it cooks or that is served with it. Sauces provide flavour, moisture, and a contrast in texture and colour. They may also serve as a medium in which food is contained, for example, the velouté sauce of creamed chicken.`,
        unit: '210gm',
        stock: 100,
        tags: ['life', 'soya', 'sauce'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710413/MBbazar/Products/Life-Soya-Sauce-Light-210ml_iyqvfr.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710413/MBbazar/Products/images_8_pejizq.jpg',
        ],
        featured: ['popular', 'dealsOfTheDay', 'bestSell'],
        category: 'Sauce',
        sold: 4,
    },
    {
        title: 'Ahmed Mango Pickle',
        price: 15,
        offerPrice: 13,
        details: `The acetic acid in vinegar or the lactic acid produced by brine gives the pickle its salty, sour taste. ... Bread-and-butter pickles, for example, have a distinctly sweet taste because sugar and other sweeteners are added to the brine. Like tomatoes, cucumbers (and thus, pickles) are technically fruits..`,
        unit: '400gm',
        stock: 100,
        tags: ['ahmed', 'mango', 'pickle'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710414/MBbazar/Products/Ahmed-Mango-Pickle-400g_ilvmtx.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710413/MBbazar/Products/ahmed-mengo-pickle2_p32mjq.jpg',
        ],
        featured: ['popular', 'dealsOfTheDay', 'bestSell'],
        category: 'Pickles & Condiments',
        sold: 50,
    },
    {
        title: 'Ahmed Sugar Free Orange Jelly',
        price: 11,
        offerPrice: 8,
        details: `Jams and jellies are spreads typically made from fruit, sugar, and pectin. Jelly is made with the juice of the fruit; jam uses the meat of the fruit as well. Some vegetable jellies are also produced.`,
        unit: '500gm',
        stock: 100,
        tags: ['ahmed', 'suhgar free', 'orange', 'jelly'],
        onSale: true,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/ahmed-sugar-free-orange-jelly_hkn56m.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710413/MBbazar/Products/ahmed-sugar-free-orange-jelly2_f9t12e.jpg',
        ],
        featured: [''],
        category: 'Jam & Jelly',
        sold: 500,
    },
    {
        title: 'Celebration Chocolate Box',
        price: 25,
        offerPrice: 19,
        details: `a small usually thin and flat piece (as of wood or stone) cut, struck, or flaked off. b : a small piece of food: such as. (1) : a small, thin, crisp, usually salty piece of food typically prepared by frying, baking, or drying banana chips especially : potato chip — see also corn chip.`,
        unit: '800gm',
        stock: 100,
        tags: ['celebration', 'chocolate', 'box', 'snack'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653802579/MBbazar/Products/celebration-box-chocolate_s3lebh.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710411/MBbazar/Products/celebration-box-chocolate2_y4csgl.jpg',
        ],
        featured: [''],
        category: 'Chocolate',
        sold: 60,
    },
    {
        title: 'Lays American Chips Cream and Onion',
        price: 9,
        offerPrice: 6,
        details: `a small usually thin and flat piece (as of wood or stone) cut, struck, or flaked off. b : a small piece of food: such as. (1) : a small, thin, crisp, usually salty piece of food typically prepared by frying, baking, or drying banana chips especially : potato chip — see also corn chip.`,
        unit: '25gm',
        stock: 100,
        tags: ['lays', 'american', 'chips', 'snack'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/Lays-cream-and-onion-flavor2_xh1vv7.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710410/MBbazar/Products/Lays-American-Style-Cream-And-Onion-Chips-25g_jgf2sy.jpg',
        ],
        featured: [''],
        category: 'Chips & Nuts',
        sold: 60,
    },
    {
        title: 'American Mushroom',
        price: 12,
        offerPrice: 10,
        details: `canned food - food preserved by canning. canned foods, canned goods, tinned goods. food product, foodstuff - a substance that can be used or prepared for use as food. canned meat, tinned meat - meat preserved in a can or tin.`,
        unit: '450gm',
        stock: 100,
        tags: ['mashroom', 'american', 'canned Food'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710411/MBbazar/Products/American-Garden-Mushroom-Whole-Can-425g_kw1nwk.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/american-mashroom2_wtm1kc.jpg',
        ],
        featured: [''],
        category: 'Canned Food',
        sold: 60,
    },
    {
        title: 'Dan Cake Layer Cake',
        price: 5,
        offerPrice: 4,
        details: `Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. ... The most commonly used cake ingredients include flour, sugar, eggs, butter or oil or margarine, a liquid, and a leavening agent, such as baking soda or baking powder.`,
        unit: '1box',
        stock: 100,
        tags: ['dane', 'layer', 'cake'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/Dan-Cake-Vanilla-Layer-Cake-25-5-Gm_woisma.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/dane-cake-layer-cake2_ke1jls.jpg',
        ],
        featured: [''],
        category: 'Cakes',
        sold: 10,
    },
    {
        title: 'Dan Cake Layer Cake',
        price: 5,
        offerPrice: 4,
        details: `Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. ... The most commonly used cake ingredients include flour, sugar, eggs, butter or oil or margarine, a liquid, and a leavening agent, such as baking soda or baking powder.`,
        unit: '1box',
        stock: 100,
        tags: ['dane', 'layer', 'cake'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/Dan-Cake-Vanilla-Layer-Cake-25-5-Gm_woisma.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710412/MBbazar/Products/dane-cake-layer-cake2_ke1jls.jpg',
        ],
        featured: [''],
        category: 'Cakes',
        sold: 10,
    },
    {
        title: 'Dekko Ovaltine Cookie',
        price: 3,
        offerPrice: 1,
        details: `A biscuit is a flour-based baked food product. In most countries, particularly in the Commonwealth and Ireland, biscuits are typically hard, flat and unleavened. They are usually sweet and may be made with sugar, chocolate, icing, jam, ginger or cinnamon. They can also be savoury and similar to crackers.`,
        unit: '1box',
        stock: 100,
        tags: ['dekko', 'ovaltine', 'cookie', 'biscuites'],
        onSale: false,
        images: [
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710413/MBbazar/Products/Dekko-Ovaltine-Cookies-Biscuits-330g_dmg9us.jpg',
            'https://res.cloudinary.com/mbbazar/image/upload/v1653710413/MBbazar/Products/Dekko-Ovaltine-Cookies-Biscuits-330g_dmg9us.jpg',
        ],
        featured: [''],
        category: 'Biscuites',
        sold: 230,
    },
];

export default products;
